### ISSUE TITLE
Overlays for the beer list, such as "out of stock" or "New!"

### ISSUE THREAD

**Issue by trivolutioninc** [Trivolution/MugClub-iOS#123]

**Comment by michael-mckenna** [comment]
checkbox for out of stock

**Comment by rohitmucherla** [comment]
This is complete, the only thing that is left is to pick the out of stock image - for my testing it was set to the shamrock.

**Comment by michael-mckenna** [comment]
The out of stock was for the beer list not the scanner grid view
