### ISSUE TITLE
Splitting into separate issues

### ISSUE THREAD

**Issue by trivolutioninc** [Trivolution/MugClub-iOS#173]
it didnt update till we logged out and back in for the profile page to refresh.

**Comment by trivolutioninc** [comment]
also if you log in too fast, and dont let the app load your stamps on main page it says you have no stamps on the last page

**Comment by michael-mckenna** [comment]
@trivolutioninc Ben, the only way to counter this (for this only happens after the first login), would be to disallow the user to go to the page and wait for everything to download, and this is unconventional. 

Mobile users nowadays are essentially trained to wait for everything to finish downloading before being able to access everything.
