### ISSUE TITLE
75 boxes

### ISSUE THREAD

**Issue by Joshua-Wright** [Trivolution/MugClub-iOS#3]

**Comment by michael-mckenna** [comment]
The first box is a prototype, so you have to, in the code, reuse that box 75 times and increment the number inside of it.

**Comment by michael-mckenna** [comment]
You'll have to create a CustomCell in the "Views" directory, and then for the collection view cell that is being reused, you will use that custom cell...let me know if you are confused about this concept.

**Comment by michael-mckenna** [comment]
https://www.youtube.com/watch?v=j3lwTzPBoLw

**Comment by michael-mckenna** [comment]
seeing if this shows up on slack
